version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/Service/nginx/html:/usr/share/nginx/html
      - ${PWD}/Service/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/Service/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/Service/nginx/conf.d:/etc/nginx/conf.d
      - ${PWD}/Service/nginx/logs:/var/log/nginx

networks:
  default:
    external:
      name: nginx-net
