version: "3"
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    expose:
      - "443"
    volumes:
      - ${PWD}:/etc/v2ray
      - ${PWD}/logs:/var/log/v2ray
networks:
  default:
    external:
      name: nginx-net
